/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as ContinueRouteImport } from './routes/continue'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as ReadBookIdRouteImport } from './routes/read.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinueRoute = ContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookIdRoute = ReadBookIdRouteImport.update({
  id: '/read/$bookId',
  path: '/read/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/continue': typeof ContinueRoute
  '/knowledge': typeof KnowledgeRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/continue': typeof ContinueRoute
  '/knowledge': typeof KnowledgeRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/continue': typeof ContinueRoute
  '/knowledge': typeof KnowledgeRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/read/$bookId': typeof ReadBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio'
    | '/continue'
    | '/knowledge'
    | '/book/$bookId'
    | '/read/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio'
    | '/continue'
    | '/knowledge'
    | '/book/$bookId'
    | '/read/$bookId'
  id:
    | '__root__'
    | '/'
    | '/audio'
    | '/continue'
    | '/knowledge'
    | '/book/$bookId'
    | '/read/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioRoute: typeof AudioRoute
  ContinueRoute: typeof ContinueRoute
  KnowledgeRoute: typeof KnowledgeRoute
  BookBookIdRoute: typeof BookBookIdRoute
  ReadBookIdRoute: typeof ReadBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continue': {
      id: '/continue'
      path: '/continue'
      fullPath: '/continue'
      preLoaderRoute: typeof ContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$bookId': {
      id: '/read/$bookId'
      path: '/read/$bookId'
      fullPath: '/read/$bookId'
      preLoaderRoute: typeof ReadBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioRoute: AudioRoute,
  ContinueRoute: ContinueRoute,
  KnowledgeRoute: KnowledgeRoute,
  BookBookIdRoute: BookBookIdRoute,
  ReadBookIdRoute: ReadBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
